name: Build Documentation

on:
  push:
    branches:
      - main  # Build docs on pushes to the main branch
  pull_request:
    branches:
      - main  # Build docs on pull requests to the main branch

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Include documentation dependencies here (e.g., Sphinx)
        pip install -r requirements-docs.txt

    - name: Build documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html  # Adjust paths based on your project structure

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v3.1.2  # Specify a valid version
      with:
        name: documentation
        path: docs/_build/html 
